# Generated by Django 4.1.5 on 2023-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=140)),
                ('matiere', models.CharField(max_length=140)),
                ('type_creneau', models.CharField(max_length=140)),
                ('enseignant', models.CharField(max_length=140)),
                ('salle', models.CharField(max_length=140)),
                ('departement', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['promo'],
            },
        ),
    ]
