# Generated by Django 4.1.5 on 2023-01-18 19:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edt',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edt',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 1, 18, 19, 51, 41, 329633, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
