# Generated by Django 4.1.5 on 2023-01-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0003_edt_heure_debut_edt_heure_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
