# Generated by Django 4.1.5 on 2023-01-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0004_alter_edt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
