# Generated by Django 4.1.5 on 2023-01-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0007_alter_departement_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='creneau',
            name='matiere',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edt.matiere'),
        ),
    ]
