# Generated by Django 4.1.5 on 2023-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0008_matiere_alter_creneau_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
