# Generated by Django 4.1.5 on 2023-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0009_alter_promotion_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='dateString',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
