# Generated by Django 4.1.5 on 2023-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0010_creneau_datestring'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='debut',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creneau',
            name='fin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
