# Generated by Django 4.1.5 on 2023-01-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0011_creneau_debut_creneau_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='dif',
            field=models.IntegerField(null=True),
        ),
    ]
