# Generated by Django 4.1.5 on 2023-01-30 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='filiere',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='edt.filiere'),
            preserve_default=False,
        ),
    ]
