# Generated by Django 4.1.5 on 2023-01-30 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0014_creneau_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='filiere',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='edt.filiere'),
        ),
    ]
