# Generated by Django 4.1.5 on 2023-01-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0015_alter_creneau_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='filiere',
        ),
    ]
