# Generated by Django 4.1.5 on 2023-01-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0016_remove_creneau_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
