# Generated by Django 4.1.5 on 2023-01-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0017_alter_creneau_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
